stages:
  - setup
  - test
  - clean

setup_job:
  stage: setup
  only:
    - master
  script:
    - pip install -U --user numpy scipy scikit-learn hmmlearn
    - echo 'push!(LOAD_PATH, "/home/gitlab-runner/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/MSDDP/src")' > ~/.juliarc.jl

.test_template: &test_definition
  stage: test
  only:
    - master
  script:
    - /usr/bin/julia6 -e 'Pkg.clone(pwd()); Pkg.test("MSDDP",
      coverage = true)'
    - /usr/bin/julia6 -e 'Pkg.add("Coverage"); cd(Pkg.dir("MSDDP"));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

clean_job:
  stage: clean
  only:
    - master
  script:
    - /usr/bin/julia6 -e 'Pkg.rm("MSDDP")';
  when: always

# Name a test and select an appropriate image.
test:0.6:
  image: julia6
  <<: *test_definition
